# name: Lighthouse Audit

# on:
#   push:
#     branches: [main]

# jobs:
#   lighthouse:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Install Lighthouse CI
#         run: npm install -g @lhci/cli

#       - name: Run Lighthouse
#         run: lhci autorun --collect.staticDistDir=./HTML_INDIVIDUAL_EXERCISE --upload.target=temporary-public-storage

name: Lighthouse Audit

on:
  push:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse (game-lp only)
        run: lhci autorun --collect.staticDistDir=./HTML_INDIVIDUAL_EXERCISE --upload.target=temporary-public-storage